services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
  openai_starter_agent:
    build:
      context: ./backend/agent_templates/openai-starter
      dockerfile: Dockerfile
    ports:
      - "8999:8000"
    volumes:
      - ./backend/agent_templates/openai-starter:/app
    env_file:
      - ./backend/agent_templates/openai-starter/.env
    environment:
      - PYTHONUNBUFFERED=1
